apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJiMjF2YzJ0aGJHVnVhMjg2WjJod1gwNVNXblZ2Y0ZSVlNEZHNXVVZpTWtwYWFsWk1OMmRFYkhaUVNXbDRNREJMZWxsM2J3bz0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
